unit ResultadosQR;

interface

uses Windows, SysUtils, Messages, Classes, Graphics, Controls,
  StdCtrls, ExtCtrls, Forms, QuickRpt, QRCtrls;

type
  TQRResultados = class(TQuickRep)
    qrbndPortada: TQRBand;
    qrbndSummaryBand1: TQRBand;
    qrimgLogoGeneralitat: TQRImage;
    qrlbl1: TQRLabel;
    qrlblTitulo1: TQRLabel;
    qrlbl34: TQRLabel;
    qrlbl35: TQRLabel;
    qrlbl36: TQRLabel;
    qrlbl37: TQRLabel;
    qrlbl38: TQRLabel;
    qrlbl39: TQRLabel;
    qrlbl40: TQRLabel;
    qrlbl41: TQRLabel;
    qrlbl42: TQRLabel;
    qrlbl43: TQRLabel;
    qrlbl44: TQRLabel;
    qrlbl45: TQRLabel;
    qrlbl46: TQRLabel;
    qrlbl47: TQRLabel;
    qrlbl48: TQRLabel;
    qrlbl49: TQRLabel;
    qrlbl50: TQRLabel;
    qrlbl51: TQRLabel;
    qrshp1: TQRShape;
    qrlbl52: TQRLabel;
    qrlbl53: TQRLabel;
    qrlbl54: TQRLabel;
    qrlbl55: TQRLabel;
    qrlbl57: TQRLabel;
    qrlbl58: TQRLabel;
    qrlbl59: TQRLabel;
    qrlbl60: TQRLabel;
    qrimg1: TQRImage;
    qrimg2: TQRImage;
    qrshp5: TQRShape;
    QRLabel2: TQRLabel;
    QRLabel3: TQRLabel;
    QRLabel4: TQRLabel;
    qrbndDetailBand1: TQRBand;
    qrdbtxtCMN: TQRDBText;
    qrdbtxtEA: TQRDBText;
    qrdbtxtCLL: TQRDBText;
    qrdbtxtEF: TQRDBText;
    qrdbtxtVLL: TQRDBText;
    qrdbtxt1: TQRDBText;
    qrdbtxt2: TQRDBText;
    qrdbtxt3: TQRDBText;
    qrdbtxt4: TQRDBText;
    qrdbtxt5: TQRDBText;
    qrdbtxtCCSS_IN: TQRDBText;
    qrdbtxtCCSS_SU: TQRDBText;
    qrdbtxtCCSS_NT: TQRDBText;
    qrdbtxtCCSS_BI: TQRDBText;
    qrdbtxtCCSS_SB: TQRDBText;
    qrdbtxtEA_IN: TQRDBText;
    qrdbtxtEA_SU: TQRDBText;
    qrdbtxtEA_BI: TQRDBText;
    qrdbtxtEA_NT: TQRDBText;
    qrdbtxtEA_SB: TQRDBText;
    qrdbtxtEF_IN: TQRDBText;
    qrdbtxtEF_SU: TQRDBText;
    qrdbtxtEF_NT: TQRDBText;
    qrdbtxtEF_BI: TQRDBText;
    qrdbtxtEF_SB: TQRDBText;
    qrdbtxtPLE_IN: TQRDBText;
    qrdbtxtPLE_SU: TQRDBText;
    qrdbtxtPLE_BI: TQRDBText;
    qrdbtxtPLE_NT: TQRDBText;
    qrdbtxtPLE_SB: TQRDBText;
    qrdbtxtM_IN: TQRDBText;
    qrdbtxtM_SU: TQRDBText;
    qrdbtxtM_NT: TQRDBText;
    qrdbtxtM_BI: TQRDBText;
    qrdbtxtM_SB: TQRDBText;
    qrdbtxtVLL_IN: TQRDBText;
    qrdbtxtVLL_SU: TQRDBText;
    qrdbtxtVLL_BI: TQRDBText;
    qrdbtxtVLL_NT: TQRDBText;
    qrdbtxtVLL_SB: TQRDBText;
    qrdbtxtCV_SB: TQRDBText;
    qrdbtxtCV_NT: TQRDBText;
    qrdbtxtCV_BI: TQRDBText;
    qrdbtxtCV_SU: TQRDBText;
    qrdbtxtCV_IN: TQRDBText;
    qrdbtxtVSC_SB: TQRDBText;
    qrdbtxtVSC_NT: TQRDBText;
    qrdbtxtVSC_BI: TQRDBText;
    qrdbtxtVSC_SU: TQRDBText;
    qrdbtxtVSC_IN: TQRDBText;
    qrdbtxtREL_SB: TQRDBText;
    qrdbtxtREL_NT: TQRDBText;
    qrdbtxtREL_BI: TQRDBText;
    qrdbtxtREL_SU: TQRDBText;
    qrdbtxtREL_IN: TQRDBText;
    qrdbtxtP: TQRDBText;
    qrdbtxtNP: TQRDBText;
    qrdbtxtalumnos: TQRDBText;
    qrdbtxt54: TQRDBText;
    qrdbtxtANP: TQRDBText;
    qrdbtxtclase: TQRDBText;
    qrdbtxtgrupo: TQRDBText;
    qrlbl32: TQRLabel;
    qrlbl33: TQRLabel;
    qrlbl70: TQRLabel;
    qrshp13: TQRShape;
    qrlbl3: TQRLabel;
    qrshp3: TQRShape;
    qrlbl12: TQRLabel;
    qrshp4: TQRShape;
    qrlbl21: TQRLabel;
    qrshp6: TQRShape;
    qrlbl29: TQRLabel;
    qrlbl4: TQRLabel;
    qrlbl6: TQRLabel;
    qrlbl7: TQRLabel;
    qrlbl9: TQRLabel;
    qrlbl10: TQRLabel;
    qrlbl30: TQRLabel;
    qrlbl13: TQRLabel;
    qrlbl15: TQRLabel;
    qrlbl16: TQRLabel;
    qrlbl18: TQRLabel;
    qrlbl19: TQRLabel;
    qrlbl22: TQRLabel;
    qrlbl24: TQRLabel;
    qrlbl25: TQRLabel;
    qrlbl27: TQRLabel;
    qrlbl28: TQRLabel;
    qrlbl61: TQRLabel;
    qrlbl111: TQRLabel;
    qrlbl112: TQRLabel;
    qrshp7: TQRShape;
    qrlbl125: TQRLabel;
    qrshp8: TQRShape;
    qrlbl126: TQRLabel;
    qrlbl127: TQRLabel;
    qrlbl128: TQRLabel;
    qrlbl129: TQRLabel;
    qrlbl130: TQRLabel;
    qrlbl131: TQRLabel;
    qrlbl132: TQRLabel;
    qrlbl133: TQRLabel;
    qrlbl134: TQRLabel;
    qrlbl135: TQRLabel;
    qrlbl136: TQRLabel;
    qrlbl137: TQRLabel;
    qrlbl17: TQRLabel;
    qrshp10: TQRShape;
    qrlbl23: TQRLabel;
    qrshp11: TQRShape;
    qrlbl26: TQRLabel;
    qrlbl138: TQRLabel;
    qrlbl139: TQRLabel;
    qrlbl140: TQRLabel;
    qrlbl141: TQRLabel;
    qrlbl142: TQRLabel;
    qrlbl143: TQRLabel;
    qrlbl144: TQRLabel;
    qrlbl145: TQRLabel;
    qrlbl146: TQRLabel;
    qrlbl8: TQRLabel;
    qrshp12: TQRShape;
    qrlbl11: TQRLabel;
    qrlbl110: TQRLabel;
    qrlbl147: TQRLabel;
    qrlbl148: TQRLabel;
    qrlbl149: TQRLabel;
    qrlbl20: TQRLabel;
    qrshp14: TQRShape;
    qrlbl150: TQRLabel;
    qrlbl151: TQRLabel;
    qrlbl152: TQRLabel;
    qrlbl153: TQRLabel;
    qrlbl154: TQRLabel;
    qrlbl155: TQRLabel;
    qrshp15: TQRShape;
    qrlbl156: TQRLabel;
    qrlbl157: TQRLabel;
    qrlbl158: TQRLabel;
    qrlbl159: TQRLabel;
    qrlbl160: TQRLabel;
    qrshp2: TQRShape;
    qrshp16: TQRShape;
    qrshp17: TQRShape;
    qrlbl5: TQRLabel;
    qrlbl14: TQRLabel;
    qrlbl64: TQRLabel;
    qrlbl65: TQRLabel;
    qrlbl66: TQRLabel;
    qrlbl67: TQRLabel;
    qrlbl68: TQRLabel;
    qrlbl69: TQRLabel;
    qrlbl161: TQRLabel;
    qrlbl162: TQRLabel;
    qrlbl163: TQRLabel;
    qrlbl164: TQRLabel;
    qrshp18: TQRShape;
    qrshp19: TQRShape;
    qrshp20: TQRShape;
    qrshp21: TQRShape;
    qrshp22: TQRShape;
    qrshp23: TQRShape;
    qrshp24: TQRShape;
    qrlbl31: TQRLabel;
    qrbndPageFooterBand1: TQRBand;
    qrshp46: TQRShape;
    qrlbl83: TQRLabel;
    qrlbl80: TQRLabel;
    qrlbl81: TQRLabel;
    qrlbl82: TQRLabel;
    qrlbl62: TQRLabel;
    qrlbl63: TQRLabel;
    qrlbl84: TQRLabel;
    qrlbl85: TQRLabel;
    qrlbl88: TQRLabel;
    qrlbl89: TQRLabel;
    qrlbl113: TQRLabel;
    qrlbl114: TQRLabel;
    qrlbl115: TQRLabel;
    qrlbl116: TQRLabel;
    qrlbl117: TQRLabel;
    qrlbl118: TQRLabel;
    qrlbl119: TQRLabel;
    qrlbl120: TQRLabel;
    qrlbl121: TQRLabel;
    qrlbl122: TQRLabel;
    qrlbl96: TQRLabel;
    qrlbl124: TQRLabel;
    qrlbl101: TQRLabel;
    qrlbl102: TQRLabel;
    qrlbl104: TQRLabel;
    qrlbl105: TQRLabel;
    qrlbl107: TQRLabel;
    qrlbl108: TQRLabel;
    qrlbl2: TQRLabel;
    qrlbl56: TQRLabel;
    qrshp9: TQRShape;
    qrlbl71: TQRLabel;
    qrlbl72: TQRLabel;
    qrlbl73: TQRLabel;
    qrlbl74: TQRLabel;
    qrlbl75: TQRLabel;
    qrlbl76: TQRLabel;
    qrlbl77: TQRLabel;
    qrshp25: TQRShape;
    qrshp26: TQRShape;
    qrshp27: TQRShape;
    qrshp28: TQRShape;
    qrshp29: TQRShape;
    qrlbl78: TQRLabel;
    QRLabel1: TQRLabel;
    qrlbl79: TQRLabel;
    qrlbl86: TQRLabel;
    qrshp30: TQRShape;
    qrshp31: TQRShape;
    qrshp32: TQRShape;
    qrlbl87: TQRLabel;
    qrlbl90: TQRLabel;
    qrlbl91: TQRLabel;
    qrlbl92: TQRLabel;
    qrdbtxt6: TQRDBText;
    qrdbtxt7: TQRDBText;
    qrdbtxt8: TQRDBText;
    qrdbtxt9: TQRDBText;
    qrdbtxt10: TQRDBText;
    qrdbtxt11: TQRDBText;
    qrdbtxt12: TQRDBText;
    qrdbtxt13: TQRDBText;
    qrdbtxt14: TQRDBText;
    qrdbtxt15: TQRDBText;
    qrdbtxt16: TQRDBText;
    qrdbtxt17: TQRDBText;
    qrdbtxt18: TQRDBText;
    qrdbtxt19: TQRDBText;
    qrdbtxt20: TQRDBText;
    qrdbtxt21: TQRDBText;
    qrdbtxt22: TQRDBText;
    qrdbtxt23: TQRDBText;
    qrdbtxt24: TQRDBText;
    qrdbtxt25: TQRDBText;
    qrdbtxt26: TQRDBText;
    qrdbtxt27: TQRDBText;
    qrdbtxt28: TQRDBText;
    qrdbtxt29: TQRDBText;
    qrdbtxt30: TQRDBText;
    qrdbtxt31: TQRDBText;
    qrdbtxt32: TQRDBText;
    qrdbtxt33: TQRDBText;
    qrdbtxt34: TQRDBText;
    qrdbtxt35: TQRDBText;
    qrdbtxt36: TQRDBText;
    qrdbtxt37: TQRDBText;
    qrdbtxt38: TQRDBText;
    qrdbtxt39: TQRDBText;
    qrdbtxt40: TQRDBText;
    qrdbtxt41: TQRDBText;
    qrdbtxt42: TQRDBText;
    qrdbtxt43: TQRDBText;
    qrdbtxt44: TQRDBText;
    qrdbtxt45: TQRDBText;
    qrdbtxt46: TQRDBText;
    qrdbtxt47: TQRDBText;
    qrdbtxt48: TQRDBText;
    qrdbtxt49: TQRDBText;
    qrdbtxt50: TQRDBText;
    qrdbtxt51: TQRDBText;
    qrdbtxt52: TQRDBText;
    qrdbtxt53: TQRDBText;
    qrdbtxt56: TQRDBText;
    qrdbtxt57: TQRDBText;
    qrdbtxt58: TQRDBText;
    qrdbtxt59: TQRDBText;
    qrdbtxt60: TQRDBText;
    qrdbtxt61: TQRDBText;
    qrdbtxt62: TQRDBText;
    qrdbtxt63: TQRDBText;
    qrdbtxt64: TQRDBText;
    qrdbtxt65: TQRDBText;
    qrdbtxt66: TQRDBText;
    qrdbtxt67: TQRDBText;
    qrdbtxtclase1: TQRDBText;
    qrdbtxtgrupo1: TQRDBText;
    qrshp33: TQRShape;
    qrdbtxt70: TQRDBText;
    qrdbtxt71: TQRDBText;
    qrdbtxt72: TQRDBText;
    qrdbtxt73: TQRDBText;
    qrdbtxt74: TQRDBText;
    qrdbtxt75: TQRDBText;
    qrdbtxt76: TQRDBText;
    qrdbtxt77: TQRDBText;
    qrdbtxt78: TQRDBText;
    qrdbtxt79: TQRDBText;
    qrdbtxtCS_IN: TQRDBText;
    qrdbtxtCS_SU: TQRDBText;
    qrdbtxtCS_NT: TQRDBText;
    qrdbtxtCS_BI: TQRDBText;
    qrdbtxtCS_SB: TQRDBText;
    qrdbtxt85: TQRDBText;
    qrdbtxt86: TQRDBText;
    qrdbtxt87: TQRDBText;
    qrdbtxt88: TQRDBText;
    qrdbtxt89: TQRDBText;
    qrdbtxt90: TQRDBText;
    qrdbtxt91: TQRDBText;
    qrdbtxt92: TQRDBText;
    qrdbtxt93: TQRDBText;
    qrdbtxt94: TQRDBText;
    qrdbtxtIN_IN: TQRDBText;
    qrdbtxtIN_SU: TQRDBText;
    qrdbtxtIN_BI: TQRDBText;
    qrdbtxtIN_NT: TQRDBText;
    qrdbtxtIN_SB1: TQRDBText;
    qrdbtxt100: TQRDBText;
    qrdbtxt101: TQRDBText;
    qrdbtxt102: TQRDBText;
    qrdbtxt103: TQRDBText;
    qrdbtxt104: TQRDBText;
    qrdbtxt105: TQRDBText;
    qrdbtxt106: TQRDBText;
    qrdbtxt107: TQRDBText;
    qrdbtxt108: TQRDBText;
    qrdbtxt109: TQRDBText;
    qrdbtxt110: TQRDBText;
    qrdbtxt111: TQRDBText;
    qrdbtxt112: TQRDBText;
    qrdbtxt113: TQRDBText;
    qrdbtxt114: TQRDBText;
    qrdbtxt115: TQRDBText;
    qrdbtxt116: TQRDBText;
    qrdbtxt117: TQRDBText;
    qrdbtxt118: TQRDBText;
    qrdbtxt119: TQRDBText;
    qrdbtxt120: TQRDBText;
    qrdbtxt121: TQRDBText;
    qrdbtxt122: TQRDBText;
    qrdbtxt123: TQRDBText;
    qrdbtxt124: TQRDBText;
    qrdbtxt125: TQRDBText;
    qrdbtxt126: TQRDBText;
    qrdbtxt127: TQRDBText;
    qrdbtxtAP: TQRDBText;
    qrdbtxtANP1: TQRDBText;
    qrlbl94: TQRLabel;
    qrshp34: TQRShape;
    qrshp35: TQRShape;
    qrgrp1: TQRGroup;
    qrbndTotales: TQRBand;
    qrdbtxt130: TQRDBText;
    qrdbtxt131: TQRDBText;
    qrdbtxt132: TQRDBText;
    qrdbtxt133: TQRDBText;
    qrdbtxt134: TQRDBText;
    qrdbtxt135: TQRDBText;
    qrdbtxt136: TQRDBText;
    qrdbtxt137: TQRDBText;
    qrdbtxt138: TQRDBText;
    qrdbtxt139: TQRDBText;
    qrdbtxtCS_IN1: TQRDBText;
    qrdbtxtCS_SU1: TQRDBText;
    qrdbtxtCS_NT1: TQRDBText;
    qrdbtxtCS_BI1: TQRDBText;
    qrdbtxtCS_SB1: TQRDBText;
    qrdbtxt145: TQRDBText;
    qrdbtxt146: TQRDBText;
    qrdbtxt147: TQRDBText;
    qrdbtxt148: TQRDBText;
    qrdbtxt149: TQRDBText;
    qrdbtxt150: TQRDBText;
    qrdbtxt151: TQRDBText;
    qrdbtxt152: TQRDBText;
    qrdbtxt153: TQRDBText;
    qrdbtxt154: TQRDBText;
    qrdbtxtIN_IN1: TQRDBText;
    qrdbtxtIN_SU1: TQRDBText;
    qrdbtxtIN_BI1: TQRDBText;
    qrdbtxtIN_NT1: TQRDBText;
    qrdbtxtIN_SB: TQRDBText;
    qrdbtxt160: TQRDBText;
    qrdbtxt161: TQRDBText;
    qrdbtxt162: TQRDBText;
    qrdbtxt163: TQRDBText;
    qrdbtxt164: TQRDBText;
    qrdbtxt165: TQRDBText;
    qrdbtxt166: TQRDBText;
    qrdbtxt167: TQRDBText;
    qrdbtxt168: TQRDBText;
    qrdbtxt169: TQRDBText;
    qrdbtxt170: TQRDBText;
    qrdbtxt171: TQRDBText;
    qrdbtxt172: TQRDBText;
    qrdbtxt173: TQRDBText;
    qrdbtxt174: TQRDBText;
    qrdbtxt175: TQRDBText;
    qrdbtxt176: TQRDBText;
    qrdbtxt177: TQRDBText;
    qrdbtxt178: TQRDBText;
    qrdbtxt179: TQRDBText;
    qrdbtxt180: TQRDBText;
    qrdbtxt181: TQRDBText;
    qrdbtxt182: TQRDBText;
    qrdbtxt183: TQRDBText;
    qrdbtxt184: TQRDBText;
    qrdbtxt185: TQRDBText;
    qrdbtxt186: TQRDBText;
    qrdbtxt187: TQRDBText;
    qrdbtxtAP1: TQRDBText;
    qrdbtxtANP2: TQRDBText;
    qrshp36: TQRShape;
    qrlbl97: TQRLabel;
    qrshpCV: TQRShape;
    qrlbl93: TQRLabel;
    qrlbl99: TQRLabel;
    qrlbl100: TQRLabel;
    qrlbl103: TQRLabel;
    qrlbl106: TQRLabel;
    qrlbl109: TQRLabel;
    qrmNotas: TQRMemo;
    qrlbl95: TQRLabel;
    qrlbl98: TQRLabel;
    qrlbl123: TQRLabel;
    qrlbl165: TQRLabel;
    qrlbl166: TQRLabel;
    procedure PrintClase(sender: TObject; var Value: String);
    procedure PrintAnyo(sender: TObject; var Value: String);
    procedure PrintFecha(sender: TObject; var Value: String);
    procedure PrintDirector(sender: TObject; var Value: String);
    procedure PrintTitulo(sender: TObject; var Value: String);
    procedure PrintTutor(sender: TObject; var Value: String);
    procedure PrintLocalidad(sender: TObject; var Value: String);
    procedure QuickRepBeforePrint(Sender: TCustomQuickRep;
      var PrintReport: Boolean);
    procedure qrgrp1BeforePrint(Sender: TQRCustomBand;
      var PrintBand: Boolean);
    procedure qrbndDetailBand1BeforePrint(Sender: TQRCustomBand;
      var PrintBand: Boolean);
    procedure qrdbtxtCV_INPrint(sender: TObject; var Value: String);
    procedure qrdbtxtclase1Print(sender: TObject; var Value: String);
    procedure qrdbtxtclasePrint(sender: TObject; var Value: String);
    procedure qrdbtxtPPrint(sender: TObject; var Value: String);
  private

  public
    iTrimestre, iALumnos, iPromocionan: Integer;
    sClase, sAnyo, sDirector, sTutor: string;
    dFecha: TDateTime;
    

  end;               

implementation

{$R *.DFM}

uses
   UDMResultados;

procedure TQRResultados.PrintTitulo(sender: TObject; var Value: String);
begin
 //
end;

procedure TQRResultados.PrintLocalidad(sender: TObject; var Value: String);
begin
  Value:= 'El Campello, ' + FormatDateTime('dd" de "mmmm" de "yyyy', dFecha )+ '.';
end;

procedure TQRResultados.PrintClase(sender: TObject; var Value: String);
begin
  Value:= sClase;
end;

procedure TQRResultados.PrintAnyo(sender: TObject; var Value: String);
begin
  Value:= sAnyo;
end;

procedure TQRResultados.PrintFecha(sender: TObject; var Value: String);
begin
  Value:= FormatDateTime('dd/mm/yyyy', dFecha );
end;

procedure TQRResultados.PrintDirector(sender: TObject; var Value: String);
begin
  Value:= sDirector;
end;

procedure TQRResultados.PrintTutor(sender: TObject; var Value: String);
begin
  Value:= sTutor;
end;


procedure TQRResultados.QuickRepBeforePrint(Sender: TCustomQuickRep;
  var PrintReport: Boolean);
begin
  qrbndSummaryBand1.Height:= 733;
  //qrbndSummaryBand1.Height:= 0;
end;

procedure TQRResultados.qrgrp1BeforePrint(Sender: TQRCustomBand;
  var PrintBand: Boolean);
begin
  qrgrp1.Height:= 0;
end;

procedure TQRResultados.qrbndDetailBand1BeforePrint(Sender: TQRCustomBand;
  var PrintBand: Boolean);
begin
  qrshpCV.Enabled:= DataSet.FieldByName('clase').AsString <> '05';
end;

procedure TQRResultados.qrdbtxtCV_INPrint(sender: TObject;
  var Value: String);
begin
  //TQRDBText( sender ).Enabled:= DataSet.FieldByName('clase').AsString = '05';
end;

procedure TQRResultados.qrdbtxtclase1Print(sender: TObject;
  var Value: String);
begin
  Value:= '...';
end;

procedure TQRResultados.qrdbtxtclasePrint(sender: TObject;
  var Value: String);
var
  iAux: Integer;
begin
  if TryStrToInt(Value, iAux) then
    Value:= IntToStr( iAux );
end;

procedure TQRResultados.qrdbtxtPPrint(sender: TObject; var Value: String);
begin
  if Value = '-1' then
    Value:= '';
end;

end.
